### ISSUE TITLE
Error: Invalid resource type

### ISSUE THREAD

**Issue by mamedos** [Namecheap-Ecosystem/terraform-provider-namecheap#22]
Error: Invalid resource type

  on xx.tf line 117, in resource "namecheap_domain_dns" "mydns":
 117: resource "namecheap_domain_dns" "mydns" {

The provider provider.namecheap does not support resource type

**Comment by itsezc** [comment]
+1 exists on Terraform 0.14.0

```
❯ terraform -v
Terraform v0.14.10
+ provider registry.terraform.io/namecheap-ecosystem/namecheap v0.1.5
```

**Comment by diraol** [comment]
Same here using terraform `v0.15.0` and `namecheap v0.1.5`.

**Comment by KeisukeYamashita** [comment]
Sorry for the inconvenience. Will take a look soon

**Comment by KeisukeYamashita** [comment]
Hi, I fixed it in https://github.com/Namecheap-Ecosystem/terraform-provider-namecheap/pull/26 and will release 0.1.6 soon. Thank you for your patience.

**Comment by diraol** [comment]
Sure thing, thanks for it!
