### ISSUE TITLE
import does not set domain attribute?

### ISSUE THREAD

**Issue by oebeledrijfhout** [Namecheap-Ecosystem/terraform-provider-namecheap#29]
I'm a beginner with Terraform, please bear with me if I make some wrong assumptions. I'm using this provider in a module named `namecheap_ns`. I ran `terraform import module.namecheap_ns.namecheap_domain_dns.ns example.co`. It looks like the `domain` attribute is then set to  `null` in `terraform.tfstate`. In any case, `terraform apply` results in the crash below:

When I manually edit `terraform.tfstate` and set the domain to `example.co` (fake name), `terraform apply` finishes with 0 updates, as expected.

```
tiemen@WS01:~/workspace/terraform-domains$ terraform apply
module.cloudflare.cloudflare_zone.zone: Refreshing state... [id=xxxxxxxxxxxxxxxxxxxxxxxx]
module.namecheap_ns.namecheap_domain_dns.ns: Refreshing state... [id=example.co]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.namecheap_ns.namecheap_domain_dns.ns will be updated in-place
  ~ resource "namecheap_domain_dns" "ns" {
      + domain      = "example.co"
        id          = "example.co"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.namecheap_ns.namecheap_domain_dns.ns: Modifying... [id=example.co]
╷
│ Error: Plugin did not respond
│
│   with module.namecheap_ns.namecheap_domain_dns.ns,
│   on modules/namecheap_ns/main.tf line 10, in resource "namecheap_domain_dns" "ns":
│   10: resource "namecheap_domain_dns" "ns" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-namecheap_v0.1.6 plugin:

panic: interface conversion: interface {} is []interface {}, not *schema.Set

goroutine 54 [running]:
github.com/Namecheap-Ecosystem/terraform-provider-namecheap/namecheap.resourceDomainDNSUpdate(0xda8b00, 0xc00032ef00, 0xc00017f100, 0xc9d6c0, 0xc000309f20, 0xc000333ae0, 0x87a5aa, 0xc0004747c0)
        github.com/Namecheap-Ecosystem/terraform-provider-namecheap/namecheap/resource_domain_dns.go:76 +0x398
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003f00e0, 0xda8a80, 0xc00034a140, 0xc00017f100, 0xc9d6c0, 0xc000309f20, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:364 +0x17c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f00e0, 0xda8a80, 0xc00034a140, 0xc00018c3f0, 0xc0004747c0, 0xc9d6c0, 0xc000309f20, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000388180, 0xda8a80, 0xc00034a140, 0xc000334820, 0xc00034a140, 0x0, 0xdb28a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8cf
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000205b60, 0xda8a80, 0xc00034a140, 0xc00018c1c0, 0xc000205b60, 0xc000330b10, 0xc0005eeba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc7c580, 0xc000205b60, 0xda8b40, 0xc000330b10, 0xc00032e360, 0x0, 0xda8b40, 0xc000330b10, 0xc00034c000, 0x132)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200, 0xc000096690, 0x11dd260, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000aa190, 0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-namecheap_v0.1.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by diraol** [comment]
I'm seeing it too!

**Comment by RaimundasR** [comment]
Hi all,

I'm getting same error message :( 

using this one

`resource "namecheap_domain_dns" "mydns" {
    domain = "domain.com"

    nameservers = [
        "xx.ns.cloudflare.com",
        "xx.ns.cloudflare.com",
    ]
}`

**Comment by RaimundasR** [comment]
> I'm a beginner with Terraform, please bear with me if I make some wrong assumptions. I'm using this provider in a module named `namecheap_ns`. I ran `terraform import module.namecheap_ns.namecheap_domain_dns.ns example.co`. It looks like the `domain` attribute is then set to `null` in `terraform.tfstate`. In any case, `terraform apply` results in the crash below:
> 
> When I manually edit `terraform.tfstate` and set the domain to `example.co` (fake name), `terraform apply` finishes with 0 updates, as expected.
> 
> ```
> tiemen@WS01:~/workspace/terraform-domains$ terraform apply
> module.cloudflare.cloudflare_zone.zone: Refreshing state... [id=xxxxxxxxxxxxxxxxxxxxxxxx]
> module.namecheap_ns.namecheap_domain_dns.ns: Refreshing state... [id=example.co]
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   # module.namecheap_ns.namecheap_domain_dns.ns will be updated in-place
>   ~ resource "namecheap_domain_dns" "ns" {
>       + domain      = "example.co"
>         id          = "example.co"
>         # (1 unchanged attribute hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> module.namecheap_ns.namecheap_domain_dns.ns: Modifying... [id=example.co]
> ╷
> │ Error: Plugin did not respond
> │
> │   with module.namecheap_ns.namecheap_domain_dns.ns,
> │   on modules/namecheap_ns/main.tf line 10, in resource "namecheap_domain_dns" "ns":
> │   10: resource "namecheap_domain_dns" "ns" {
> │
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> 
> Stack trace from the terraform-provider-namecheap_v0.1.6 plugin:
> 
> panic: interface conversion: interface {} is []interface {}, not *schema.Set
> 
> goroutine 54 [running]:
> github.com/Namecheap-Ecosystem/terraform-provider-namecheap/namecheap.resourceDomainDNSUpdate(0xda8b00, 0xc00032ef00, 0xc00017f100, 0xc9d6c0, 0xc000309f20, 0xc000333ae0, 0x87a5aa, 0xc0004747c0)
>         github.com/Namecheap-Ecosystem/terraform-provider-namecheap/namecheap/resource_domain_dns.go:76 +0x398
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003f00e0, 0xda8a80, 0xc00034a140, 0xc00017f100, 0xc9d6c0, 0xc000309f20, 0x0, 0x0, 0x0)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:364 +0x17c
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f00e0, 0xda8a80, 0xc00034a140, 0xc00018c3f0, 0xc0004747c0, 0xc9d6c0, 0xc000309f20, 0x0, 0x0, 0x0, ...)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:464 +0x390
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000388180, 0xda8a80, 0xc00034a140, 0xc000334820, 0xc00034a140, 0x0, 0xdb28a0)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8cf
> github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000205b60, 0xda8a80, 0xc00034a140, 0xc00018c1c0, 0xc000205b60, 0xc000330b10, 0xc0005eeba0)
>         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xae
> github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc7c580, 0xc000205b60, 0xda8b40, 0xc000330b10, 0xc00032e360, 0x0, 0xda8b40, 0xc000330b10, 0xc00034c000, 0x132)
>         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200, 0xc000096690, 0x11dd260, 0x0, 0x0, 0x0)
>         google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
> google.golang.org/grpc.(*Server).handleStream(0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200, 0x0)
>         google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
> google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000aa190, 0xc0003ac540, 0xdb0620, 0xc000586c00, 0xc00018a200)
>         google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
> created by google.golang.org/grpc.(*Server).serveStreams.func1
>         google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
> 
> Error: The terraform-provider-namecheap_v0.1.6 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.
> ```

Hi, just would like to as, do you still have same issue, or did u find any solution, Im also new with terraform , so cant find any other providers for terraform regarding namecheap custom Dns.

**Comment by vertis** [comment]
I think the error message you're seeing is misleading you. I've seen the same thing, where the import doesn't set the domain, and if you manually update the state it goes to no changes.

However, if you then change anything else (say the name servers) it returns to the same error where the call the plugin fails. This indicates to me that the two issues are not related.

Doesn't help with using the plugin though.

**Comment by vertis** [comment]
I've fixed the issue in PR #30. So as soon as @KeisukeYamashita reviews and hopefully merges it, it should work again.

**Comment by RaimundasR** [comment]
Now all good with resource "namecheap_domain_dns" "mydns", thank you @KeisukeYamashita  @vertis for the help :)

**Comment by KeisukeYamashita** [comment]
thank you all!🙇🏻‍♂️🙇🏻‍♂️
